apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: spring-boot-dewey
  name: spring-boot-dewey
spec:
  replicas: 5
  selector:
    matchLabels:
      run: spring-boot-dewey
  template:
    metadata:
      labels:
        run: spring-boot-dewey
    spec:
      containers:
      - image: ${IMAGE}
        name: app
